### ISSUE TITLE
Zonemaster fails on FreeBSD after update of Perl to 5.34

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#1197]
Default Perl on FreeBSD has been updated from 5.32 to 5.34. From output of `pkg`:

```
Installed packages to be UPGRADED:
(...)
        perl5: 5.32.1_4 -> 5.34.1_3
```

After the update of Perl Zonemaster will fail. Here it is illustrated with `zonemaster-cli` but it will affect any installation of Zonemaster on FreeBSD.

```
$ zonemaster-cli iis.se
Can't locate Zonemaster/LDNS.pm in @INC (you may need to install the 
Zonemaster::LDNS module) (@INC contains: 
/usr/local/lib/perl5/site_perl/mach/5.34 /usr/local/lib/perl5/site_perl 
/usr/local/lib/perl5/5.34/mach /usr/local/lib/perl5/5.34) at 
/usr/local/lib/perl5/site_perl/Zonemaster/Engine/Nameserver.pm line 14.
BEGIN failed--compilation aborted at 
/usr/local/lib/perl5/site_perl/Zonemaster/Engine/Nameserver.pm line 14.
Compilation failed in require at 
/usr/local/lib/perl5/site_perl/Zonemaster/Engine.pm line 19.
BEGIN failed--compilation aborted at 
/usr/local/lib/perl5/site_perl/Zonemaster/Engine.pm line 19.
Compilation failed in require at 
/usr/local/lib/perl5/site_perl/Zonemaster/CLI.pm line 29.
BEGIN failed--compilation aborted at 
/usr/local/lib/perl5/site_perl/Zonemaster/CLI.pm line 29.
Compilation failed in require at /usr/local/bin/zonemaster-cli line 6.
BEGIN failed--compilation aborted at /usr/local/bin/zonemaster-cli line 6.
Command: zonemaster-cli iis.se failed!
```

The solution is to reinstall Zonemaster-LDNS. The command is found under https://github.com/zonemaster/zonemaster/blob/master/docs/public/installation/zonemaster-engine.md#installation-on-freebsd:
```
# cpanm --notest --configure-args="--no-internal-ldns" Zonemaster::LDNS
--> Working on Zonemaster::LDNS
Fetching http://www.cpan.org/authors/id/Z/ZN/ZNMSTR/ Zonemaster-LDNS-3.2.0.tar.gz
... OK
Configuring Zonemaster-LDNS-3.2.0 ... OK
Building Zonemaster-LDNS-3.2.0 ... OK
Successfully installed Zonemaster-LDNS-3.2.0
1 distribution installed
```

Now it will work again. If it is an installation with a Zonemaster daemon, such as Zonemaster-Backend, the daemon must be restarted.

**Comment by marc-vanderwal** [comment]
I presume that this happens because Zonemaster::LDNS uses XS to hook into perl’s innards, and that the interpreter’s API may change from version to version. Hence the need for recompiling.

If we had a FreeBSD port for Zonemaster::LDNS, the corresponding binary package is automatically forced to be rebuilt at each new minor version of Perl (I use poudriere at home, so I’ve seen this happen several times over). Then, updating `perl` using `pkg` would also trigger a forced reinstallation of the hypothetical `p5-Zonemaster-LDNS` package.
